# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("owning does not resolve",
     "            record.state = G_RESOLVED\n", "            record.state = G_OPEN\n"),
    ("attempt cap off by one (4 attempts)",
     "if int(record.attempts) >= MAX_ATTEMPTS:", "if int(record.attempts) > MAX_ATTEMPTS:"),
    ("deflect does not spend an attempt",
     "record.attempts = u256(int(record.attempts) + 1)", "record.attempts = u256(int(record.attempts))"),
    ("fail-safe flipped on unparseable output",
     "                    return {\"outcome\": DEFLECTS}\n            if not isinstance(data, dict):",
     "                    return {\"outcome\": OWNS_IT}\n            if not isinstance(data, dict):"),
    ("unknown label maps to OWNS_IT",
     "            if outcome == OWNS_IT:\n                return {\"outcome\": OWNS_IT}\n            return {\"outcome\": DEFLECTS}",
     "            if outcome == DEFLECTS:\n                return {\"outcome\": DEFLECTS}\n            return {\"outcome\": OWNS_IT}"),
    ("validator accepts any valid label",
     "                return str(mine.get(\"outcome\", \"\")).strip().upper() == leader_outcome",
     "                return True"),
    ("anyone may answer",
     "        if caller != record.respondent:\n            raise gl.vm.UserError(\"Only the named respondent may answer this grievance\")",
     "        if caller == \"\":\n            raise gl.vm.UserError(\"Only the named respondent may answer this grievance\")"),
    ("anyone may withdraw",
     "        if caller != str(record.complainant).lower():", "        if caller == \"\":"),
    ("same answer may be reused",
     "        if seen in self.answer_seen:", "        if seen in self.answer_seen and False:"),
    ("answer_seen keyed on raw text (whitespace grinding)",
     "        seen = self._seen_key(gid, self._normalize_text(clean))", "        seen = self._seen_key(gid, text)"),
    ("open-pair guard missing",
     "        if self.open_pair.get(pair, \"\") != \"\":", "        if False:"),
    ("pair not freed on resolve",
     "            self._bump(self.resolved_by_owning, record.respondent)\n            self.open_pair[pair] = \"\"",
     "            self._bump(self.resolved_by_owning, record.respondent)"),
    ("standing not written on close",
     "                self._bump(self.closed_unanswered, record.respondent)\n", ""),
    ("reserved token not checked on answers",
     "            raise gl.vm.UserError(\"Answer is too long\")\n        if self._contains_reserved_token(clean):",
     "            raise gl.vm.UserError(\"Answer is too long\")\n        if False:"),
    ("fence strip: no gap and a single pass (cross-token rebuild survives)",
     "            cleaned = cleaned[:index] + \" \" + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        # Fixed point: repeat until nothing changes, so nested fragments\n        # such as \"<<TAG>TAG>\" cannot rebuild a marker after one pass.\n        cleaned = value\n        while True:\n            before = cleaned\n            for token in RESERVED_TOKENS:\n                cleaned = self._remove_token(cleaned, token)\n            if cleaned == before:\n                return \" \".join(cleaned.split())",
     "            cleaned = cleaned[:index] + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        cleaned = value\n        for token in RESERVED_TOKENS:\n            cleaned = self._remove_token(cleaned, token)\n        return \" \".join(cleaned.split())"),
    ("wallet leaks into the prompt",
     "        safe_answer = self._fence_strip(answer_text)",
     "        safe_answer = self._fence_strip(answer_text) + \" \" + str(gl.message.sender_address)"),
    ("state checked after caller",
     "        if record.state != G_OPEN:\n            raise gl.vm.UserError(\"This grievance is no longer open\")\n        caller = str(gl.message.sender_address).lower()\n        if caller != record.respondent:",
     "        caller = str(gl.message.sender_address).lower()\n        if caller != record.respondent:\n            raise gl.vm.UserError(\"Only the named respondent may answer this grievance\")\n        if record.state != G_OPEN:\n            raise gl.vm.UserError(\"This grievance is no longer open\")\n        if caller != record.respondent:"),
    ("id ignores whitespace normalization",
     "        gid = self._grievance_id(caller, respondent, self._normalize_text(clean))",
     "        gid = self._grievance_id(caller, respondent, clean)"),
    ("complaint length cap off by one",
     "        if len(clean) > MAX_COMPLAINT_LENGTH:", "        if len(clean) >= MAX_COMPLAINT_LENGTH:"),
]
